export const SUPPORTED_LANGUAGES = [
  { code: "en", name: "English", rtl: false },
  { code: "es", name: "Spanish", rtl: false },
  { code: "fr", name: "French", rtl: false },
  { code: "de", name: "German", rtl: false },
  { code: "it", name: "Italian", rtl: false },
  { code: "pt", name: "Portuguese", rtl: false },
  { code: "ru", name: "Russian", rtl: false },
  { code: "ja", name: "Japanese", rtl: false },
  { code: "ko", name: "Korean", rtl: false },
  { code: "zh", name: "Chinese (Simplified)", rtl: false },
  { code: "zh-TW", name: "Chinese (Traditional)", rtl: false },
  { code: "ar", name: "Arabic", rtl: true },
  { code: "he", name: "Hebrew", rtl: true },
  { code: "fa", name: "Persian", rtl: true },
  { code: "ur", name: "Urdu", rtl: true },
  { code: "hi", name: "Hindi", rtl: false },
  { code: "th", name: "Thai", rtl: false },
  { code: "vi", name: "Vietnamese", rtl: false },
  { code: "nl", name: "Dutch", rtl: false },
  { code: "pl", name: "Polish", rtl: false },
  { code: "tr", name: "Turkish", rtl: false },
  { code: "sv", name: "Swedish", rtl: false },
  { code: "da", name: "Danish", rtl: false },
  { code: "fi", name: "Finnish", rtl: false },
  { code: "no", name: "Norwegian", rtl: false },
  { code: "id", name: "Indonesian", rtl: false },
  { code: "ms", name: "Malay", rtl: false },
  { code: "bn", name: "Bengali", rtl: false },
  { code: "uk", name: "Ukrainian", rtl: false },
  { code: "cs", name: "Czech", rtl: false },
  { code: "el", name: "Greek", rtl: false },
  { code: "ro", name: "Romanian", rtl: false },
  { code: "hu", name: "Hungarian", rtl: false },
  { code: "sk", name: "Slovak", rtl: false },
  { code: "bg", name: "Bulgarian", rtl: false },
  { code: "hr", name: "Croatian", rtl: false },
  { code: "lt", name: "Lithuanian", rtl: false },
  { code: "sl", name: "Slovenian", rtl: false },
  { code: "et", name: "Estonian", rtl: false },
  { code: "lv", name: "Latvian", rtl: false },
  { code: "ca", name: "Catalan", rtl: false },
  { code: "tl", name: "Filipino", rtl: false },
  { code: "sw", name: "Swahili", rtl: false },
  { code: "ta", name: "Tamil", rtl: false },
  { code: "te", name: "Telugu", rtl: false },
  { code: "mr", name: "Marathi", rtl: false },
  { code: "gu", name: "Gujarati", rtl: false },
  { code: "kn", name: "Kannada", rtl: false },
  { code: "ml", name: "Malayalam", rtl: false },
] as const;

export const RTL_LANGUAGES = SUPPORTED_LANGUAGES.filter((l) => l.rtl).map(
  (l) => l.code
);

export function isRTL(langCode: string): boolean {
  return (RTL_LANGUAGES as readonly string[]).includes(langCode);
}
